---
title: "7th Tidy Tuesday"
author: "Ruth Vergara Reyes"
date: "4/20/2021"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

#Introduction 

My plot is inspired by Rebecca Stevick, who posted her plot on twitter. 
https://twitter.com/rjstevick/status/1384574073737515011?s=21 

# Load Libraries 
```{r}
library(tidyverse)
library(hrbrthemes)
library(ggimage)
library(ggtext)
library(here)
```


# Load Data
```{r}
tidy_data <- tidytuesdayR::tt_load(2021, week = 17)
netflix_data <- tidy_data$netflix_titles
## This weeks data

images <- tibble(image=c("https://i.pinimg.com/originals/87/9f/35/879f354dfe3834de15865303aa22995a.png"))   
## cartoon image of the TV for plot
```


# Cleaning up the Data 
```{r}
clean_netflix <- netflix_data %>%
  filter(type == "Movie")%>%                  ## selecting only movies 
  separate(col = date_added,
           into = c("month", "day", "year"),
           sep = " ")%>%                      ## How I extracted the date
  select(-cast, -month, -day,
         -release_year, -description)%>%      ## removing columns that I don't need
  rename(year_added = year)%>%                ## renaming the year to better describe the column
  separate_rows(listed_in, sep = ", ")%>%
  filter(listed_in != "International Movies",
         listed_in != "Movies",
         listed_in != "Independent Movies",
         listed_in != "Dramas",
         listed_in != "Comedies")%>%          ## How I filtered down the data to be more detailed  
  mutate(listed_in = recode(listed_in, 
                            "Classic Movies" = "Classics",
                            "Children & Family Movies" = "Children & Family",
                            "Sports Movies" = "Sports",
                            "Romantic Movies" = "Romantic",
                            "Horror Movies" = "Horror",
                            "LGBTQ Movies" = "LGBTQ",
                            "Anime Features" = "Anime",
                            "Cult Movies" = "Cults"))%>%      ## How I renamed characters within columns
  separate(col = duration,
           into = c("duration_min", "min"),
           sep = " ")%>%                      ## How I got duration to be numerical 
  select(-min) %>%                            ## Getting rid of the column that is empty
  write_csv(here("tidy_tuesday_7", "data", "netflix_data.csv"))  ## saving the new data into a csv file

netflix_2021_data <- clean_netflix %>%
  filter(year_added != 2008, year_added != 2013,
         year_added != 2009, year_added != 2014,
         year_added != 2010, year_added != 2015,
         year_added != 2011, year_added != 2016,
         year_added != 2012, year_added != 2017,
         year_added != 2018, year_added != 2019)%>%  ## getting rid of the years I don't want for the plot
  write_csv(here("tidy_tuesday_7", "data", "netflix_2020_2021_data.csv"))  ## saving the new data into a csv file

```


# Making the Plot
```{r}
netflix_2021_data %>%
  ggplot(aes(x = 1,
             y = 1))+                                ## Making the beginning of the plots 
  scale_x_continuous(limits = c(-0.4, 0.4))+         ## Making limitations for the axis                      
  scale_y_continuous(limits = c(-0.5, 0.5))+         ## Making limitations for the axis 
  facet_wrap(~listed_in, ncol = 5)+                  ## going to facet wrap by the genre of the movie
  geom_image(data = images, 
             aes(x=0.01, y=0.20,                     ## Determining the middle of the x/y axis within the image
                 image = image),      
             size = 1.3, by="height")+               ## Determining the size of the background image (cartoon tv)
  annotate("rect", 
           xmin = -0.40, ymin = -0.21, xmax = 0.32, ymax = 0.48,   ## Determining the limits of the plot 
           fill = "black", color = "black")+         ## Making the background of the plot black and determining the diameters
  geom_jitter(aes(x = -0.02,
                  y = 0,
                  color = rating),                   ## making the colors based on the ratings of the films.
              shape = 20, width = 0.35, height = 0.2,## determining the size of the points 
              color = "red")+                        ## determining the color of the points in the plot
  stat_summary(aes(color = rating, 
                   x = 0, y = 0.40, 
                   label = listed_in),               ## Making the headings for each plot
               fun = "mean", 
               geom = "text", 
               size = 2.7, 
               color = "white", 
               lineheight = 0.8)+                    ## Editing the writing within the plot
  coord_cartesian(clip = 'off')+                     ## To ensure nothing gets cut off 
  theme(legend.position = "none",                    ## getting rid of any legend
        panel.spacing = unit(1.2, "lines"),          ## making the space between the images/plots
        plot.background = element_rect(fill = "black"),            ## Making entire panel background white
        panel.background = element_rect(fill = "black"),           ## Maing the plots behind the images black 
        strip.text = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(),
        plot.title = element_markdown(hjust = 0.5,  
                                      size = 30, 
                                      color = "white"))+           ## Editing theme elements of the plot
  labs(title = "Movies added to <span style='color:red;'>**Netflix**</span> 2020/2021",
       x = NULL, y = NULL)                                         ## editing the title of the plot


ggsave(here("tidy_tuesday_7", "output", "Netflix_plot.png"),
       width = 10, height = 7)                                    ## saving the plot  into the output folder   
  

```

